server:
  port: 8080


spring:
  application:
    name: userManagement

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom
    username: root
    password: Wyb68319373*

  flyway:
    enabled: true
    locations: classpath:db
    baselineOnMigrate: true


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.commons
  type-handlers-package: com.userManagement.typeHandler