server:
  port: 8080


spring:
  application:
    name: userManagement

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom
    username: root
    password: Wyb68319373*

  rabbitmq:
    host: 192.168.40.128
    port: 5672
    username: manager
    password: 123456
    virtual-host: wyb

  data:
    redis:
      database: 0
      host: 192.168.40.128
      password: 123456
      port: 6379
      timeout: 60000

#  flyway:
#    enabled: true
#    locations: classpath:db
#    baselineOnMigrate: true
#    repeatable-sql-migration-prefix: "R"


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.commons.entities
  type-handlers-package: com.commons.typeHandler


eureka:
  instance:
    instance-id: user-management
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/


connection:
  exchange-name: connection